# Generated by Django 5.0.2 on 2024-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library_app', '0002_rename_librarygames_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=255, verbose_name='Название игры'),
        ),
    ]
