# Generated by Django 5.0.2 on 2024-03-02 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delete',
            field=models.BooleanField(default=False, help_text='Состояние удалена ли данная запись', verbose_name='Удален'),
        ),
    ]
