# Generated by Django 5.0.2 on 2024-03-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user_app', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
